Ajh javadoc
hms-networks/sc-flexy-file-util-lib pull request #4
Opened 2020-04-13 17:49 UTC by alexjhawk

2020-04-13 17:59 UTC, TomKimsey requested changes

2020-04-13 17:59 UTC, TomKimsey commented on README.md
> +A library of utility classes for accessing, modifying and working with files on Ewon Flexy.
missing oxford comma

2020-04-13 18:03 UTC, alexjhawk commented on README.md
> +A library of utility classes for accessing, modifying and working with files on Ewon Flexy.
added

2020-04-13 18:05 UTC, TomKimsey submitted a review, later dismissed

2020-04-13 18:17 UTC, alexjhawk commented
added index.html to URL

2020-04-13 18:19 UTC, TomKimsey approved these changes

2020-04-14 15:23 UTC, oliver-walker-hms approved these changes

2020-04-14 15:23 UTC, merged